LifePlanner/Models/Jelo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LifePlanner.Models
{
    public class Jelo
    {
        [Key]
        [Required]
        public Guid Id { get; set; }

        [Required]
        public string Naziv { get; set; }

        [EnumDataType(typeof(KategorijaJela))]
     
        [Display(Name = "Kategorija jela: ")]
        public KategorijaJela Kategorija { get; set; }
      
        public IList<string> Sastojci { get; set; }

        public RegistrovaniKorisnik Korisnik { get; set; }
    }
}

LifePlanner/Controllers/JeloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LifePlanner.Data;
using LifePlanner.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace LifePlanner.Controllers
{
    [Authorize]
    public class JeloController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<RegistrovaniKorisnik> _userManager;

        public JeloController(ApplicationDbContext context, UserManager<RegistrovaniKorisnik> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [ActionName("Index")]
        public async Task<IActionResult> Index()
        {
            var korisnik = await _userManager.GetUserAsync(User);
            IEnumerable<Jelo> jelaKorisnika = await _context.Jela.Where(j => j.Korisnik.Id == korisnik.Id).ToListAsync();
            return View("JelaPoKategorijama", jelaKorisnika);
        }

        [HttpPost, ActionName("DodajUKategoriju")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> dodajJeloUKategoriju(int kategorija, Guid idJela)
        {
            KategorijaJela _kategorija = (KategorijaJela)kategorija;
            Jelo jelo = await _context.Jela.SingleOrDefaultAsync
                (j => j.Id == idJela);
            if(jelo == null)
            {
                return RedirectToAction("Index");
            }
            jelo.Kategorija = _kategorija;
            _context.Update(jelo);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");        
        }

        // GET: Jelo
        [ActionName("SvaJela")]
        public async Task<IActionResult> IndexSvaJela()
        {
            var kor = await _userManager.GetUserAsync(User);
            string id = kor.Id;
            IEnumerable<Jelo> jelaOdKorisnika = await _context.Jela.Where(
                j => id == j.Korisnik.Id
            ).ToListAsync();

            return View("Index", jelaOdKorisnika);
        }

        // GET: Jelo/Details/5
        [ActionName("Details")]
        public async Task<IActionResult> Index(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jelo = await _context.Jela
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jelo == null)
            {
                return NotFound();
            }

            return View(jelo);
        }

        // GET: Jelo/Create
        [ActionName("Create")]
        public IActionResult DodajJelo()
        {
            return View();
        }

        // POST: Jelo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DodajJelo([Bind("Id,Naziv,Sastojci")] Jelo jelo)
        {
            if (ModelState.IsValid)
            {
                jelo.Id = Guid.NewGuid();
                
                RegistrovaniKorisnik trenutni = await _userManager.GetUserAsync(User);
                jelo.Korisnik = trenutni;

                if (jelo.Sastojci == null)
                {
                    jelo.Sastojci = new List<string>();
                }
                else
                {
                    jelo.Sastojci = jelo.Sastojci.Where(v => v != null).ToList();
                }

                jelo.Sastojci = jelo.Sastojci.Where(s => s != null).ToList();

                _context.Add(jelo);
                await _context.SaveChangesAsync();
                return RedirectToAction("SvaJela");
            }
            return View(jelo);
        }

        // GET: Jelo/Edit/5
        [ActionName("Edit")]
        public async Task<IActionResult> UrediJelo(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jelo = await _context.Jela.FindAsync(id);
            if (jelo == null)
            {
                return NotFound();
            }
            return View(jelo);
        }

        // POST: Jelo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UrediJelo(Guid id, [Bind("Id,Naziv,Sastojci")] Jelo jelo)
        {
            if (id != jelo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    jelo.Sastojci = jelo.Sastojci.Where(s => s != null).ToList();
                    _context.Update(jelo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JeloExists(jelo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("SvaJela");
            }
            return View(jelo);
        }

        // GET: Jelo/Delete/5
        [ActionName("Delete")]
        public async Task<IActionResult> ObrisiJelo(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jelo = await _context.Jela
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jelo == null)
            {
                return NotFound();
            }

            return View(jelo);
        }

        // POST: Jelo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ObrisiJelo(Guid id)
        {
            var jelo = await _context.Jela.FindAsync(id);
            _context.Jela.Remove(jelo);
            await _context.SaveChangesAsync();
            return RedirectToAction("SvaJela");
        }

        private bool JeloExists(Guid id)
        {
            return _context.Jela.Any(e => e.Id == id);
        }
    }
}

LifePlanner/Views/Jelo/Create.cshtml
@model LifePlanner.Models.Jelo

@{
    ViewData["Title"] = "Kreiranje jela";
}

<h1>Kreiranje jela</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
        <button onclick="addRow()" type="button">Dodaj sastojak</button>
            <table id="SastojciTabela">
                <tr>
                </tr>
            </table>
            <div class="form-group">
                <input type="submit" value="Spasi" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="SvaJela">Nazad na listu</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
        <script>
            window.counter = 0;
        </script>
        <script src="~/js/tabelaZaUnos.js"></script>
}

LifePlanner/Views/Jelo/Delete.cshtml
@model LifePlanner.Models.Jelo

@{
    ViewData["Title"] = "Brisanje jela";
}

<h1>Brisanje jela</h1>

<h3>Jeste li sigurni da želite da obrišete ovo jelo?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kategorija)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kategorija)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sastojci)
        </dt>
        <dd class = "col-sm-10">
            <table>
                @foreach (var sastojak in Model.Sastojci)
                {
                    if (sastojak.Length == 0) continue;
                    <tr style="">@sastojak</tr><br/>
                }
            </table>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Obriši" class="btn btn-danger" /> |
        <a asp-action="SvaJela">Nazad na listu</a>
    </form>
</div>

LifePlanner/Views/Jelo/Details.cshtml
@model LifePlanner.Models.Jelo

@{
    ViewData["Title"] = "Opis jela";
}

<h1>Opis jela</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kategorija)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kategorija)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sastojci)
        </dt>
        <dd class = "col-sm-10">
            <table>
                @for (int i = 0; i < Model.Sastojci.Count; i++)
                {
                    @:<tr>
                        @Model.Sastojci[i]
                    @:</tr></br>
                }
            </table>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Uredi</a> |
    <a asp-action="SvaJela">Nazad na listu jela</a> |
    <a asp-action="">Nazad na kategorije</a>
</div>

LifePlanner/Views/Jelo/DodajJeloUKategoriju.cshtml
@model IEnumerable<LifePlanner.Models.Jelo>

@{ ViewData["Title"] = "DodajJeloUKategoriju";
}

LifePlanner/Views/Jelo/Edit.cshtml
@model LifePlanner.Models.Jelo

@{
    ViewData["Title"] = "Uređivanje jela";
}

<h1>Uređivanje jela</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <button onclick="addRow()" type="button">Dodaj sastojak</button>
            </br>
            <table id="SastojciTabela">
                <tr>
                    <th></th>
                </tr>
                @for (int i = 0; i < Model.Sastojci.Count; i++)
                {
                    @:<tr>
                        @:<input type="text" name="Sastojci[@i]" value="@Model.Sastojci[i]" />
                        @:<input type="button" id="Sastojci[@i]" onclick="obrisi(this)" value="Obrisi" /">
                    @:</tr>
                }
            </table>
            <div class="form-group">
                <input type="submit" value="Spasi" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="SvaJela">Nazad na listu</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>
        window.counter = @Model.Sastojci.Count;
</script>
<script src="~/js/tabelaZaUnos.js"></script>
}

LifePlanner/Views/Jelo/Index.cshtml
@model IEnumerable<LifePlanner.Models.Jelo>

@{
    ViewData["Title"] = "Jela";
    int i = 0;
}

<div id="naslov">
    <h1>Jela</h1>
    <form asp-action="Create" style="display:inline;" method="get" id="dodaj">
        <button class="btn btn-light">Dodaj novo</button>
    </form>
    <form asp-action="" style="display:inline;" method="get" id="kategorije">
        <button class="btn btn-light">Pregled po kategorijama</button>
    </form>
</div>

<div id="jela">
    @foreach (var jelo in Model)
    {
        <div class="jelo">
            <h2>@jelo.Naziv</h2>
            <hr />
            <div class="vjezbe">
                @foreach (var sastojak in jelo.Sastojci)
                {
                    if (i == 3)
                    {
                        break;
                    }
                    i++;
                    <p>@sastojak</p>
                }
                @{ i = 0; }
            </div>
            <hr />
            <div class="dugmad">
                <form asp-action="Edit" style="display:inline;" method="get">
                    <input type="text" name="id" value="@jelo.Id" hidden />
                    <button class="btn btn-secondary">Uredi</button>
                </form>
                <form asp-action="Details" style="display:inline;" method="get">
                    <input type="text" name="id" value="@jelo.Id" hidden />
                    <button class="btn btn-info">Detaljnije</button>
                </form>
                <form asp-action="Delete" style="display:inline;" method="get">
                    <input type="text" name="id" value="@jelo.Id" hidden />
                    <button class="btn btn-danger">Obriši</button>
                </form>

            </div>
        </div>
    }
</div>



<!--

<a asp-action="Create">Kreiraj novi</a>

    -->
@section Styles {
    <link rel="stylesheet" href="~/css/jela.css" />
}

LifePlanner/Views/Jelo/JelaPoKategorijama.cshtml
@model IEnumerable<LifePlanner.Models.Jelo>

@{
    ViewData["Title"] = "JelaPoKategorijama";
}

<div id="naslov">
    <h1>Jela po kategorijama</h1>
    <form asp-action="SvaJela" style="display:inline;" method="get">
        <button class="btn btn-light">Pregled svih jela</button>
    </form>
</div>

<div id="kategorije">
    <div id="dorucak">
        <h2>Doručak</h2>
        @if (Model.Count() != 0)
        {
            <div class="kategorija">
                @if (!Model.All(j => j.Kategorija == KategorijaJela.Dorucak))
                {
                    <div class="dugmad">
                        <form asp-action="DodajUKategoriju" method="post" class="formaDodavanje">
                            <input type="hidden" name="kategorija" value="1">
                            <select name="idJela">
                                @foreach (var item in Model)
                                {
                                    if (item.Kategorija == KategorijaJela.Dorucak) continue;
                                    <option value="@item.Id">@item.Naziv</option>
                                }
                            </select>
                            <input type="submit" value="Dodaj jelo" class="btn btn-md btn-light" />
                            @Html.AntiForgeryToken()
                        </form>
                    </div>
                }
                @foreach (var item in Model)
                {
                    if (item.Kategorija == KategorijaJela.Dorucak)
                    {
                        <form asp-action="DodajUKategoriju" method="post" class="jelo">
                            <p class="@item.Naziv">
                                @item.Naziv
                                <input type="button" name="Opis" value="Opis jela" class="btn btn-sm btn-info" onclick="location.href='@Url.Action("Details", "Jelo", new { id = item.Id })'  " />
                            </p>
                            <input type="hidden" name="kategorija" value="0" style="display: inline;">
                            <input type="hidden" name="idJela" value="@item.Id" style="display: inline;">
                            <input type="submit" value="Ukloni jelo" style="display: inline;" class="btn btn-sm btn-danger" />
                            @Html.AntiForgeryToken()
                        </form>
                    }
                }
            </div>
        }
    </div>

    <div id="rucak">
        <h2>Ručak</h2>
        @if (Model.Count() != 0)
        {
            <div class="kategorija">
                @if (!Model.All(j => j.Kategorija == KategorijaJela.Rucak))
                {
                    <div class="dugmad">
                        <form asp-action="DodajUKategoriju" method="post" class="formaDodavanje">
                            <input type="hidden" name="kategorija" value="2">
                            <select name="idJela">
                                @foreach (var item in Model)
                                {
                                    if (item.Kategorija == KategorijaJela.Rucak) continue;
                                    <option value="@item.Id">@item.Naziv</option>
                                }
                            </select>
                            <input type="submit" value="Dodaj jelo" class="btn btn-md btn-light" />
                            @Html.AntiForgeryToken()
                        </form>
                    </div>
                }
                @foreach (var item in Model)
                {
                    if (item.Kategorija == KategorijaJela.Rucak)
                    {
                        <form asp-action="DodajUKategoriju" method="post" class="jelo">
                            <p class="@item.Naziv">
                                @item.Naziv
                                <input type="button" name="Opis" value="Opis jela" class="btn btn-sm btn-info" onclick="location.href='@Url.Action("Details", "Jelo", new { id = item.Id })'  " />
                            </p>
                            <input type="hidden" name="kategorija" value="0" style="display: inline;">
                            <input type="hidden" name="idJela" value="@item.Id" style="display: inline;">
                            <input type="submit" value="Ukloni jelo" style="display: inline;" class="btn btn-sm btn-danger" />
                            @Html.AntiForgeryToken()
                        </form>
                    }
                }
            </div>
        }
    </div>


    <div id="vecera">
        <h2>Večera</h2>
        @if (Model.Count() != 0)
        {
        <div class="kategorija">
            @if (!Model.All(j => j.Kategorija == KategorijaJela.Vecera))
            {
                <div class="dugmad">
                    <form asp-action="DodajUKategoriju" method="post" class="formaDodavanje">
                        <input type="hidden" name="kategorija" value="3">
                        <select name="idJela">
                            @foreach (var item in Model)
                            {
                                if (item.Kategorija == KategorijaJela.Vecera) continue;
                                <option value="@item.Id">@item.Naziv</option>
                            }
                        </select>
                        <input type="submit" value="Dodaj jelo" class="btn btn-md btn-light" />
                        @Html.AntiForgeryToken()
                    </form>
                </div>
            }
            @foreach (var item in Model)
            {
                if (item.Kategorija == KategorijaJela.Vecera)
                {
                    <form asp-action="DodajUKategoriju" method="post" class="jelo">
                        <p class="@item.Naziv">
                            @item.Naziv
                            <input type="button" name="Opis" value="Opis jela" class="btn btn-sm btn-info" onclick="location.href='@Url.Action("Details", "Jelo", new { id = item.Id })'  " />
                        </p>
                        <input type="hidden" name="kategorija" value="0" style="display: inline;">
                        <input type="hidden" name="idJela" value="@item.Id" style="display: inline;">
                        <input type="submit" value="Ukloni jelo" style="display: inline;" class="btn btn-sm btn-danger" />
                        @Html.AntiForgeryToken()
                    </form>
                }
            }
        </div>
        }
    </div>
</div>


<!--
<h1>Jela po kategorijama</h1>
<a asp-controller="Jelo" asp-action="SvaJela">Lista svih jela</a>
<hr />
<div id="sveKategorije">
    <div id="dorucak" class="kategorija">
        <h2>Doručak</h2>
        @foreach (var item in Model)
        {
            if (item.Kategorija == KategorijaJela.Dorucak)
            {
                <form asp-action="DodajUKategoriju" method="post" style="margin: 0; padding: 0;">
                    <p class="@item.Naziv">
                        @item.Naziv
                        <input type="hidden" name="kategorija" value="0" style="display: inline;">
                        <input type="hidden" name="idJela" value="@item.Id" style="display: inline;">
                        <input type="submit" value="Ukloni jelo" style="display: inline;" />
                    </p>
                    @Html.AntiForgeryToken()
                </form>
            }
        }
        @if (Model.Count() != 0)
        {
            <div class="dodavanjeNovog">
                <form asp-action="DodajUKategoriju" method="post">
                    <input type="hidden" name="kategorija" value="1">
                    <select name="idJela">
                        @foreach (var item in Model)
                        {
                            <option value="@item.Id">@item.Naziv</option>
                        }
                    </select>
                    <input type="submit" value="Dodaj jelo" />
                    @Html.AntiForgeryToken()
                </form>
            </div>
        }

    </div>
    <div id="rucak" class="kategorija">
        <h2>Ručak</h2>
        @foreach (var item in Model)
        {
            if (item.Kategorija == KategorijaJela.Rucak)
            {
                <form asp-action="DodajUKategoriju" method="post" style="margin: 0; padding: 0;">
                    <p class="@item.Naziv">
                        @item.Naziv
                        <input type="hidden" name="kategorija" value="0" style="display: inline;">
                        <input type="hidden" name="idJela" value="@item.Id" style="display: inline;">
                        <input type="submit" value="Ukloni jelo" style="display: inline;" />
                    </p>
                    @Html.AntiForgeryToken()
                </form>
            }
        }
        @if (Model.Count() != 0)
        {
            <div class="dodavanjeNovog">
                <form asp-action="DodajUKategoriju" method="post">
                    <input type="hidden" name="kategorija" value="2">
                    <select name="idJela">
                        @foreach (var item in Model)
                        {
                            <option value="@item.Id">@item.Naziv</option>
                        }
                    </select>
                    <input type="submit" value="Dodaj jelo" />
                    @Html.AntiForgeryToken()
                </form>
            </div>
        }

    </div>
    <div id="Vecera" class="kategorija">
        <h2>Večera</h2>
        @foreach (var item in Model)
        {
            if (item.Kategorija == KategorijaJela.Vecera)
            {
                <form asp-action="DodajUKategoriju" method="post" style="margin: 0; padding: 0;">
                    <p class="@item.Naziv">
                        @item.Naziv
                        <input type="hidden" name="kategorija" value="0" style="display: inline;">
                        <input type="hidden" name="idJela" value="@item.Id" style="display: inline;">
                        <input type="submit" value="Ukloni jelo" style="display: inline;" />
                    </p>
                    @Html.AntiForgeryToken()
                </form>
            }
        }
        @if (Model.Count() != 0)
        {
            <div class="dodavanjeNovog">
                <form asp-action="DodajUKategoriju" method="post">
                    <input type="hidden" name="kategorija" value="3">
                    <select name="idJela">
                        @foreach (var item in Model)
                        {
                            <option value="@item.Id">@item.Naziv</option>
                        }
                    </select>
                    <input type="submit" value="Dodaj jelo" />
                    @Html.AntiForgeryToken()
                </form>
            </div>
        }
    </div>
</div>
    -->
@section Styles {
    <link rel="stylesheet" href="~/css/JelaPoKategorijama.css" />
} 