LifePlanner/Models/Zadatak.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LifePlanner.Models
{
    public class Zadatak
    {
        [Key]
        [Required]
        public Guid Id { get; set; }

        [Required]
        public string Naziv { get; set; }

        [DataType(DataType.Date)]
        [Required]
        [Display(Name = "Datum: ")]
        public DateTime Datum { get; set; }

        public RegistrovaniKorisnik Korisnik { get; set; }
    }
}

LifePlanner/Controllers/MoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LifePlanner.Data;
using LifePlanner.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace LifePlanner.Controllers
{
    [Authorize]
    public class MoodController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<RegistrovaniKorisnik> _userManager;

        public MoodController(ApplicationDbContext context, UserManager<RegistrovaniKorisnik> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Mood
        public async Task<IActionResult> Index(string datumString)
        {
            DateTime datum = DateTime.ParseExact(datumString, "d_M_yyyy", null);
            var korisnik = await _userManager.GetUserAsync(User);
            var moodVecPostoji = await _context.Raspolozenja.FirstOrDefaultAsync(r => r.Datum == datum && r.Korisnik == korisnik);
            ViewBag.datum = datum.ToString("d.M.yyyy");
            ViewBag.datumFull = datum;
            return View(moodVecPostoji);
        }


        // POST: Mood/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Datum,TipRaspolozenja")] Raspolozenje raspolozenje)
        {
            if (ModelState.IsValid)
            {
                raspolozenje.Id = Guid.NewGuid();
                raspolozenje.Korisnik = await _userManager.GetUserAsync(User);
                _context.Add(raspolozenje);
                await _context.SaveChangesAsync();
                string referer = Request.Headers["Referer"].ToString();

                //posto se dodavanje novog raspolozenja odvija i iz Zadatak kontrolera i odavde, moramo uraditi redirect na referera, a ne striktno na index Mood-a
                return Redirect(referer);
                //return RedirectToAction(nameof(Index), new { datumString = raspolozenje.Datum.ToString("d_M_yyyy") });
            }
            return RedirectToAction(nameof(Index), new { datumString = DajDatumZaParametra(DateTime.UtcNow.AddHours(2)) });
        }

        // POST: Mood/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Datum,TipRaspolozenja")] Raspolozenje raspolozenje)
        {
            if (id != raspolozenje.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(raspolozenje);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RaspolozenjeExists(raspolozenje.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                string referer = Request.Headers["Referer"].ToString();
                //posto se dodavanje novog raspolozenja odvija i iz Zadatak kontrolera i odavde, moramo uraditi redirect na referera, a ne striktno na index Mood-a
                return Redirect(referer);
                //return RedirectToAction(nameof(Index), new { datumString = raspolozenje.Datum.ToString("d_M_yyyy") });
            }
            return RedirectToAction(nameof(Index), new { datumString = DajDatumZaParametra(DateTime.UtcNow.AddHours(2)) });
        }

        private bool RaspolozenjeExists(Guid id)
        {
            return _context.Raspolozenja.Any(e => e.Id == id);
        }

        private string DajDatumZaParametra(DateTime datum)
        {
            return datum.ToString("d_M_yyyy");
        }
    }
}

LifePlanner/Controllers/ZadatakController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LifePlanner.Data;
using LifePlanner.Models;
using Microsoft.AspNetCore.Identity;
using LifePlanner.Utility;

namespace LifePlanner.Controllers
{
    public class ZadatakController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<RegistrovaniKorisnik> _userManager;
        private readonly List<string> savjeti = new List<string>
        {
            "No matter how busy you may think you are, you must find time for reading, or surrender yourself to self-chosen ignorance.",
            "The authority of those who teach is often an obstacle to those who want to learn.",
            "To acquire knowledge, one must study; but to acquire wisdom, one must observe.",
            "Ne upisujte RMA"
        };

        public ZadatakController(ApplicationDbContext context, UserManager<RegistrovaniKorisnik> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public class ViewModel
        {
            public string Savjet { get; set; }
            public DateTime OdabraniDatum { get; set; }
            public DateTime DanasnjiDatum { get { return DateTime.Today; } }
            public RegistrovaniKorisnik Korisnik { get; set; }
            public List<Zadatak> taskoviZaDan { get; set; }
            public Raspolozenje Raspolozenje { get; set; }
        };

        // GET: Zadatak
        public async Task<IActionResult> Index(string datumString)
        {
            ViewModel viewModel = new ViewModel();

            DateTime datum = DateTime.ParseExact(datumString, "d_M_yyyy", null);
            var korisnik = await _userManager.GetUserAsync(User);
            List<Zadatak> taskoviZaDan = new List<Zadatak> { };

            if (korisnik == null)
            {
                taskoviZaDan = HttpContext.Session.GetObjectFromJson<List<Zadatak>>("NeRegZadaci");
                if (taskoviZaDan == null)
                {
                    taskoviZaDan = new List<Zadatak> { };
                }
            }
            else
            {
                taskoviZaDan = await _context.Zadaci.Where(z => z.Datum == datum && z.Korisnik == korisnik).ToListAsync();
            }

            //https://stackoverflow.com/questions/30887367/how-to-compare-sql-datetime-and-c-sharp-datetime
            DateTime RuzniNepotrebniDatum = DateTime.ParseExact(DateTime.Today.ToString("d_M_yyyy"), "d_M_yyyy", null);

            var raspolozenje = await _context.Raspolozenja.FirstOrDefaultAsync(r => r.Datum == RuzniNepotrebniDatum && r.Korisnik == korisnik);

            viewModel.Korisnik = korisnik;
            viewModel.Savjet = savjeti[new Random().Next(savjeti.Count)];
            viewModel.OdabraniDatum = datum;
            viewModel.taskoviZaDan = taskoviZaDan;
            viewModel.Raspolozenje = raspolozenje;
            return View(viewModel);
        }

        // POST: Zadatak/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naziv,Datum")] Zadatak zadatak)
        {
            if (ModelState.IsValid)
            {
                zadatak.Id = Guid.NewGuid();
                RegistrovaniKorisnik korisnik = await _userManager.GetUserAsync(User);

                //spasi u sesiju umjesto bazu
                if (korisnik == null)
                {
                    List<Zadatak> postojeciTaskovi = HttpContext.Session.GetObjectFromJson<List<Zadatak>>("NeRegZadaci");
                    if (postojeciTaskovi == null)
                    {
                        postojeciTaskovi = new List<Zadatak> { };
                    }
                    postojeciTaskovi.Add(zadatak);
                    HttpContext.Session.SetObjectAsJson("NeRegZadaci", postojeciTaskovi);
                    return RedirectToAction(nameof(Index), new { datumString = DajDatumZaParametra(zadatak.Datum) });
                }



                zadatak.Korisnik = korisnik;
                _context.Add(zadatak);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { datumString = DajDatumZaParametra(zadatak.Datum) });
            }
            return RedirectToAction(nameof(Index), new { datumString = DajDatumZaParametra(DateTime.UtcNow.AddHours(2)) });
        }

        // POST: Zadatak/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Naziv,Datum")] Zadatak zadatak)
        {
            if (id != zadatak.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(zadatak);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ZadatakExists(zadatak.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { datumString = DajDatumZaParametra(zadatak.Datum) });
            }
            return RedirectToAction(nameof(Index), new { datumString = DajDatumZaParametra(DateTime.UtcNow.AddHours(2)) });
        }

        // POST: Zadatak/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                List<Zadatak> postojeciTaskovi = HttpContext.Session.GetObjectFromJson<List<Zadatak>>("NeRegZadaci");
                Zadatak zadatak1 = postojeciTaskovi.FirstOrDefault(z => z.Id == id);
                postojeciTaskovi.Remove(zadatak1);
                HttpContext.Session.SetObjectAsJson("NeRegZadaci", postojeciTaskovi);
                return RedirectToAction(nameof(Index), new { datumString = DajDatumZaParametra(zadatak1.Datum) });
            }
            var zadatak = await _context.Zadaci.FindAsync(id);
            _context.Zadaci.Remove(zadatak);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { datumString = DajDatumZaParametra(zadatak.Datum) });
        }

        public IActionResult Test()
        {
            return Content(DateTime.Now.ToString() + "\n" + DateTime.UtcNow.AddHours(2).ToString());
        }

        private bool ZadatakExists(Guid id)
        {
            return _context.Zadaci.Any(e => e.Id == id);
        }

        private string DajDatumZaParametra(DateTime datum)
        {
            return datum.ToString("d_M_yyyy");
        }
    }
}

LifePlanner/Views/Zadatak/Delete.cshtml
@model LifePlanner.Models.Trening

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trening</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vjezbe)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vjezbe)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LifePlanner/Views/Zadatak/Index.cshtml
@model LifePlanner.Controllers.ZadatakController.ViewModel;

@{
    ViewData["Title"] = "Zadaci";
    Layout = "_layout";
}

<div id="glavno">
    <div id="savjet">
        <h2>Savjet</h2>
        <p style="text-align: center;">@Model.Savjet</p>
    </div>
    <hr />
    <div id="zadaci">
        <h2>Zadaci</h2>
        <form asp-action="Create" method="POST">
            <input type="text" name="Naziv" />
            <input type="datetime" name="Datum" value="@Model.OdabraniDatum" hidden />
            <input type="submit" value="Dodaj zadatak" class="btn btn-primary" style="margin-top: 5px;"/>
            @Html.AntiForgeryToken()
        </form>
        @foreach (var item in Model.taskoviZaDan)
        {
            <form asp-action="Delete" method="POST">
                <p class="@item.Naziv">
                    @item.Naziv
                    <input type="hidden" name="id" value="@item.Id" style="display: inline;">
                    <input type="submit" value="Završi zadatak" style="display: inline;" class="btn btn-outline-danger"/>
                </p>
                @Html.AntiForgeryToken()
            </form>
        }
    </div>


    <div class="calendar light">
        <div class="calendar-header">
            <span class="month-picker" id="month-picker">February</span>
            <div class="year-picker">
                <span class="year-change" id="prev-year">
                    <pre><</pre>
                </span>
                <span id="year">2021</span>
                <span class="year-change" id="next-year">
                    <pre>></pre>
                </span>
            </div>
        </div>
        <div class="calendar-body">
            <div class="calendar-week-day">
                <div>Ned</div>
                <div>Pon</div>
                <div>Uto</div>
                <div>Sri</div>
                <div>Čet</div>
                <div>Pet</div>
                <div>Sub</div>
            </div>
            <div class="calendar-days"></div>
        </div>
        <div class="calendar-footer">
        </div>
        <div class="month-list"></div>
    </div>

    @if (User.Identity.IsAuthenticated)
    {
        <div id="kakavDan">
            <h2>Kako je prošao dan?</h2>
            <div style="display: flex; flex-direction: row; text-align: center;">
                @if (Model.Raspolozenje != null)
                {
                    <form asp-controller="Mood" asp-action="Edit" method="POST" >
                        <input type="text" name="id" value="@Model.Raspolozenje.Id" hidden />
                        <input type="datetime" name="Datum" value="@Model.DanasnjiDatum" hidden />
                        <input type="number" name="TipRaspolozenja" value="0" hidden />
                        <input type="submit" name="submit" value="Dobro" class="btn btn-outline-success"/>
                    </form>
                    <form asp-controller="Mood" asp-action="Edit" method="POST">
                        <input type="text" name="id" value="@Model.Raspolozenje.Id" hidden />
                        <input type="datetime" name="Datum" value="@Model.DanasnjiDatum" hidden />
                        <input type="number" name="TipRaspolozenja" value="1" hidden />
                        <input type="submit" name="submit" value="Srednje" class="btn btn-outline-warning"/>
                    </form>
                    <form asp-controller="Mood" asp-action="Edit" method="POST">
                        <input type="text" name="id" value="@Model.Raspolozenje.Id" hidden />
                        <input type="datetime" name="Datum" value="@Model.DanasnjiDatum" hidden />
                        <input type="number" name="TipRaspolozenja" value="2" hidden />
                        <input type="submit" name="submit" value="Loše" class="btn btn-outline-danger" />
                    </form>
                }
                else
                {
                    <form asp-controller="Mood" asp-action="Create" method="POST">
                        <input type="datetime" name="Datum" value="@Model.DanasnjiDatum" hidden />
                        <input type="number" name="TipRaspolozenja" value="0" hidden />
                        <input type="submit" name="submit" value="Dobro" class="btn btn-success"/>
                    </form>
                    <form asp-controller="Mood" asp-action="Create" method="POST">
                        <input type="datetime" name="Datum" value="@Model.DanasnjiDatum" hidden />
                        <input type="number" name="TipRaspolozenja" value="1" hidden />
                        <input type="submit" name="submit" value="Srednje" class="btn btn-warning"/>
                    </form>
                    <form asp-controller="Mood" asp-action="Create" method="POST">
                        <input type="datetime" name="Datum" value="@Model.DanasnjiDatum" hidden />
                        <input type="number" name="TipRaspolozenja" value="2" hidden />
                        <input type="submit" name="submit" value="Loše" class="btn btn-danger"/>
                    </form>
                }
            </div>
        </div>
    }
</div>


@section Scripts {
    <script src="~/js/kalendar.js"></script>
}

@section Styles {
    <link rel="stylesheet" href="~/css/kalendar.css" />
    <link rel="stylesheet" href="~/css/zadaci.css" />
}